# This file explicitly tells Netlify all build settings.
[build]
  command = "" # No build command is needed.
  publish = "/" # The root directory, where index.html is.
  functions = "netlify/functions" # The directory for serverless functions.
